export const ALL_PRODUCTS_FETCH_START = 'ALL_PRODUCTS_FETCH_START';
export const ALL_PRODUCTS_FETCH_SUCCESS = 'ALL_PRODUCTS_FETCH_SUCCESS';
export const ALL_PRODUCTS_FETCH_ERROR = 'ALL_PRODUCTS_FETCH_ERROR';
export const ALL_PRODUCTS_CLEAR = 'ALL_PRODUCTS_CLEAR';