// All Products
export const ALL_PRODUCTS_FETCH_START = 'ALL_PRODUCTS_FETCH_START';
export const ALL_PRODUCTS_FETCH_SUCCESS = 'ALL_PRODUCTS_FETCH_SUCCESS';
export const ALL_PRODUCTS_FETCH_ERROR = 'ALL_PRODUCTS_FETCH_ERROR';

// Product Information
export const PRODUCT_FETCH_START = 'PRODUCT_FETCH_START';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_ERROR = 'PRODUCT_FETCH_ERROR';

// Product Categories
export const PRODUCT_CATEGORIES_FETCH_SUCCESS = 'PRODUCT_CATEGORIES_FETCH_SUCCESS';

// Clean Errors
export const CLEAN_ERROR = 'CLEAN_ERROR';